apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app.kubernetes.io/instance: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: okteto/vote:redis
        name: vote
