apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: okteto/blog:latest
        name: blog