# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: okteto/vote
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
