apiVersion: v1
kind: Service
metadata:
  name: movies-frontend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "movies-frontend"
    port: 8080
  selector:
    app: movies-frontend
