version: '3.4'
services:
  web:
    image: okteto/django:latest
    build: .
    command: ./run_web.sh
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  worker:
    image: okteto/django:latest
    build: .
    command: ./run_celery.sh
    volumes:
      - .:/app

  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:2.8.19
    hostname: redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"