apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll
  template:
    metadata:
      labels:
        app: payroll
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 5
      containers:
      - image: okteto/payroll:latest
        name: payroll